#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.15.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [3]:
e = np.array(range(5))
e.size * e.itemsize
e.dtype

array([0, 1, 2, 3, 4])

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
n[4] = 1 #We already created a null vector of size 10 previously
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
q = np.arange(10,50)
q

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [7]:
z = np.arange(10)
z = z[::-1]
z

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [9]:
z = [1,2,0,0,4,0]
np.nonzero(z)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
np.random.random((3,3,3))

array([[[0.84867371, 0.48491234, 0.39949196],
        [0.84092021, 0.94280351, 0.69022643],
        [0.30496046, 0.40432973, 0.42822597]],

       [[0.14005631, 0.03571543, 0.88109191],
        [0.41518877, 0.79071996, 0.83457967],
        [0.7273523 , 0.02000151, 0.34666814]],

       [[0.05071705, 0.80905257, 0.88015951],
        [0.43256665, 0.03285948, 0.22892374],
        [0.49874269, 0.56320535, 0.87499031]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
a = np.random.random((10,10))
print(a.max()) #We use a.max(), much more efficient than max(a)
print(a.min())

0.9842592532962506
0.0002378888088554465


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
a = np.random.random(30)
a.mean()

0.45456413996379513

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [15]:
z = np.ones((5,5))
np.pad(z,(1,1), 'constant', constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [7]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [17]:
np.diag(np.arange(1,5),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [9]:
z = np.zeros((8,8), dtype=int)
z[::2,::2] = 1
z[1::2,1::2] = 1
z

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [74]:
# np.unravel_index to obtain the matrix with a linear shape
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [19]:
np.tile(np.array([[0,1],[1,0]]),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [126]:
# mean - std
a = np.random.normal(1, 5, 25) # Distribution centered in 1 with std 5
a = np.reshape(a, (5,5))
aSum = a.sum() #Total sum of all the elements
aMean = a.mean()
aStd = a.std()

b = (a-aMean)/aStd #Give us back a matrix center in 0 and with standard deviation 1
print(a)
print()
print(b)

[[ 4.30130461  3.57080388 -7.51070829 -0.15733669 -2.85783916]
 [-0.20514504 -6.406447   -2.41079508  6.18546542 17.13946738]
 [ 3.63811447  7.74586142  5.73610174  0.85134136  8.50316262]
 [ 5.9087117   3.8724882   1.93859229 -1.60405525 -2.93018329]
 [ 2.09349447  7.87807957  2.90345875  3.75347824  2.83525028]]

[[ 0.33596722  0.19247763 -1.98422333 -0.5398274  -1.07027724]
 [-0.54921822 -1.76731732 -0.982466    0.70606605  2.85772064]
 [ 0.2056992   1.01256893  0.61779918 -0.34169646  1.16132284]
 [ 0.65170433  0.25173638 -0.12813173 -0.82400105 -1.08448753]
 [-0.09770486  1.03854006  0.06139346  0.22835969  0.04799552]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
# NO

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [29]:
a = np.random.random((5,3))
b = np.random.random((3,2))
c = np.matmul(a, b)
print(c)

[[0.57141792 0.2316713 ]
 [1.01971849 0.93445425]
 [0.97076235 0.93365478]
 [0.35570158 0.53661261]
 [0.41017339 0.12206656]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [78]:
a = np.arange(20)
print((a<3) | (a>8))

[ True  True  True False False False False False False  True  True  True
  True  True  True  True  True  True  True  True]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [39]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

# why?
# Apparently, the two lines do not give back the same value after importing * from numpy (at least the first we are executing the cell)
# When we do from numpy import *, all the numpy functions will be accessible into the local namespace, which means that the usual sum() function is overwritten
# When using the "usual" sum function, the sum will start at -1, the second argument given, given us 9 instead of 10
# Is it usually better to do from numpy import np to be able to access both sum functions: sum() and np.sum()

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [90]:
Z = np.random.random(10)
print(Z)
Z**Z
#2 << Z >> 2 Not legal
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z Not legal

[0.27681596 0.89030533 0.96723624 0.42579687 0.28954831 0.55474571
 0.72639937 0.57543912 0.54398342 0.63679776]


array([0.27681596, 0.89030533, 0.96723624, 0.42579687, 0.28954831,
       0.55474571, 0.72639937, 0.57543912, 0.54398342, 0.63679776])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [121]:
#np.array(0) / np.array(0) #nan since np.array(0) = 0
#np.array(0) // np.array(0) #Error returned with this integer division
np.array([np.nan]).astype(int).astype(float) #Working but giving back a strangely high value
print(np.array([np.nan])) #nan
print(np.array([np.nan]).astype(int)) #nan to int does not appear to be giving anything which makes sense
print(np.array([np.nan]).astype(int).astype(float))

[nan]
[-9223372036854775808]
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [131]:
# np.copysign
# Copysign(x1, x2) changes the sign of x1 to that of x2, element-wise.
a = np.array([-1.5, -1.0, -0.5, 0-0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0])
print(np.copysign(np.ceil(np.abs(a)), a))

[-2. -1. -1.  0.  1.  1.  2.  2.  3.  3.  4.  4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [50]:
# np.intersect1d
a = np.arange(9)
b = np.arange(6)
c = [1, 4, 5, 8, 11]
print(np.intersect1d(a,c))

[1 4 5 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# NO

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [54]:
np.sqrt(-1) == np.emath.sqrt(-1)
# why?
# It does not give the same value
# This is because using the emath domain allows us to consider complex values (while we get a nan on the left hand side)
# It is easy to check by checking the value on each side of the expression:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
# We can clearly see that the two expressions are not equal

nan
1j


/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
# NO

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
# NO

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
# NO

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [141]:
# ceil, floor, trunc
a = np.random.normal(1, 5, 10)
print(a)
print(np.ceil(a))
print(np.floor(a))
print(np.trunc(a))
print(np.rint(a))
print(np.around(a))
# Of course, not all the solutions give back the same answer as they round differently, as expected

[-0.0697575  -0.61992153  7.3923262   0.63342627 -3.62913162 -7.15303257
 -5.51557988 -6.65604639 -4.36497992 -0.14979946]
[-0. -0.  8.  1. -3. -7. -5. -6. -4. -0.]
[-1. -1.  7.  0. -4. -8. -6. -7. -5. -1.]
[-0. -0.  7.  0. -3. -7. -5. -6. -4. -0.]
[-0. -1.  7.  1. -4. -7. -6. -7. -4. -0.]
[-0. -1.  7.  1. -4. -7. -6. -7. -4. -0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [156]:
a = np.zeros((5,5))
a += np.arange(5) #We don't need a 5x5 matrix thanks to the broadcasting
print(a)

[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [153]:
# np.fromiter
iterable = (x for x in np.ceil(np.random.normal(0, 5, 10))) #Any function can be used to create the integers
print(np.fromiter(iterable, int))

[-2 -4 -5  2  1  4 -2  9  5  3]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [158]:
x = np.linspace(0,1,12,endpoint=True)[1:-1] #The first and last elements are 0 and 1 and can be easily removed
print(x)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [160]:
a = np.random.random(10)
print(np.sort(a))

[0.03193639 0.05108105 0.4062441  0.49694672 0.55655727 0.60115013
 0.7666552  0.80326777 0.90993672 0.9255921 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)